/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as MainTutorialsRouteImport } from './routes/_main/tutorials'
import { Route as MainTermsRouteImport } from './routes/_main/terms'
import { Route as MainSearchRouteImport } from './routes/_main/search'
import { Route as MainResetPasswordRouteImport } from './routes/_main/reset-password'
import { Route as MainProfileRouteImport } from './routes/_main/profile'
import { Route as MainPrivacyRouteImport } from './routes/_main/privacy'
import { Route as MainLegalRouteImport } from './routes/_main/legal'
import { Route as MainForgotPasswordRouteImport } from './routes/_main/forgot-password'
import { Route as MainChronosRouteImport } from './routes/_main/chronos'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTermsIndexRouteImport } from './routes/admin/terms/index'
import { Route as AdminStickersIndexRouteImport } from './routes/admin/stickers/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminEmojisIndexRouteImport } from './routes/admin/emojis/index'
import { Route as AdminComicsIndexRouteImport } from './routes/admin/comics/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiPatreonWebhookRouteImport } from './routes/api/patreon/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminUsersManageRouteImport } from './routes/admin/users/manage'
import { Route as AdminTermsCreateRouteImport } from './routes/admin/terms/create'
import { Route as AdminStickersCreateRouteImport } from './routes/admin/stickers/create'
import { Route as AdminPostsCreateRouteImport } from './routes/admin/posts/create'
import { Route as AdminPagesSlugRouteImport } from './routes/admin/pages/$slug'
import { Route as AdminExtrasWeeklyRouteImport } from './routes/admin/extras/weekly'
import { Route as AdminExtrasTutorialsRouteImport } from './routes/admin/extras/tutorials'
import { Route as AdminExtrasFeaturedRouteImport } from './routes/admin/extras/featured'
import { Route as AdminEmojisCreateRouteImport } from './routes/admin/emojis/create'
import { Route as AdminComicsCreateRouteImport } from './routes/admin/comics/create'
import { Route as AdminChronosEditRouteImport } from './routes/admin/chronos/edit'
import { Route as MainUserIdRouteImport } from './routes/_main/user.$id'
import { Route as MainPostIdRouteImport } from './routes/_main/post.$id'
import { Route as AdminStickersIdEditRouteImport } from './routes/admin/stickers/$id.edit'
import { Route as AdminPostsEditIdRouteImport } from './routes/admin/posts/edit.$id'
import { Route as AdminEmojisIdEditRouteImport } from './routes/admin/emojis/$id.edit'
import { Route as AdminComicsEditIdRouteImport } from './routes/admin/comics/edit.$id'
import { Route as MainPostReviewsIdRouteImport } from './routes/_main/post.reviews.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainTutorialsRoute = MainTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTermsRoute = MainTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainResetPasswordRoute = MainResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPrivacyRoute = MainPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLegalRoute = MainLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainForgotPasswordRoute = MainForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainChronosRoute = MainChronosRouteImport.update({
  id: '/chronos',
  path: '/chronos',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTermsIndexRoute = AdminTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStickersIndexRoute = AdminStickersIndexRouteImport.update({
  id: '/stickers/',
  path: '/stickers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmojisIndexRoute = AdminEmojisIndexRouteImport.update({
  id: '/emojis/',
  path: '/emojis/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComicsIndexRoute = AdminComicsIndexRouteImport.update({
  id: '/comics/',
  path: '/comics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatreonWebhookRoute = ApiPatreonWebhookRouteImport.update({
  id: '/api/patreon/webhook',
  path: '/api/patreon/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersManageRoute = AdminUsersManageRouteImport.update({
  id: '/users/manage',
  path: '/users/manage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTermsCreateRoute = AdminTermsCreateRouteImport.update({
  id: '/terms/create',
  path: '/terms/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStickersCreateRoute = AdminStickersCreateRouteImport.update({
  id: '/stickers/create',
  path: '/stickers/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesSlugRoute = AdminPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtrasWeeklyRoute = AdminExtrasWeeklyRouteImport.update({
  id: '/extras/weekly',
  path: '/extras/weekly',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtrasTutorialsRoute = AdminExtrasTutorialsRouteImport.update({
  id: '/extras/tutorials',
  path: '/extras/tutorials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtrasFeaturedRoute = AdminExtrasFeaturedRouteImport.update({
  id: '/extras/featured',
  path: '/extras/featured',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmojisCreateRoute = AdminEmojisCreateRouteImport.update({
  id: '/emojis/create',
  path: '/emojis/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComicsCreateRoute = AdminComicsCreateRouteImport.update({
  id: '/comics/create',
  path: '/comics/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChronosEditRoute = AdminChronosEditRouteImport.update({
  id: '/chronos/edit',
  path: '/chronos/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainUserIdRoute = MainUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPostIdRoute = MainPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const AdminStickersIdEditRoute = AdminStickersIdEditRouteImport.update({
  id: '/stickers/$id/edit',
  path: '/stickers/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsEditIdRoute = AdminPostsEditIdRouteImport.update({
  id: '/posts/edit/$id',
  path: '/posts/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmojisIdEditRoute = AdminEmojisIdEditRouteImport.update({
  id: '/emojis/$id/edit',
  path: '/emojis/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComicsEditIdRoute = AdminComicsEditIdRouteImport.update({
  id: '/comics/edit/$id',
  path: '/comics/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainPostReviewsIdRoute = MainPostReviewsIdRouteImport.update({
  id: '/post/reviews/$id',
  path: '/post/reviews/$id',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/about': typeof MainAboutRoute
  '/chronos': typeof MainChronosRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/legal': typeof MainLegalRoute
  '/privacy': typeof MainPrivacyRoute
  '/profile': typeof MainProfileRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/search': typeof MainSearchRoute
  '/terms': typeof MainTermsRoute
  '/tutorials': typeof MainTutorialsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/admin/': typeof AdminIndexRoute
  '/post/$id': typeof MainPostIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/admin/chronos/edit': typeof AdminChronosEditRoute
  '/admin/comics/create': typeof AdminComicsCreateRoute
  '/admin/emojis/create': typeof AdminEmojisCreateRoute
  '/admin/extras/featured': typeof AdminExtrasFeaturedRoute
  '/admin/extras/tutorials': typeof AdminExtrasTutorialsRoute
  '/admin/extras/weekly': typeof AdminExtrasWeeklyRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/stickers/create': typeof AdminStickersCreateRoute
  '/admin/terms/create': typeof AdminTermsCreateRoute
  '/admin/users/manage': typeof AdminUsersManageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/patreon/webhook': typeof ApiPatreonWebhookRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/comics/': typeof AdminComicsIndexRoute
  '/admin/emojis/': typeof AdminEmojisIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/stickers/': typeof AdminStickersIndexRoute
  '/admin/terms/': typeof AdminTermsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/post/reviews/$id': typeof MainPostReviewsIdRoute
  '/admin/comics/edit/$id': typeof AdminComicsEditIdRoute
  '/admin/emojis/$id/edit': typeof AdminEmojisIdEditRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
  '/admin/stickers/$id/edit': typeof AdminStickersIdEditRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/about': typeof MainAboutRoute
  '/chronos': typeof MainChronosRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/legal': typeof MainLegalRoute
  '/privacy': typeof MainPrivacyRoute
  '/profile': typeof MainProfileRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/search': typeof MainSearchRoute
  '/terms': typeof MainTermsRoute
  '/tutorials': typeof MainTutorialsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof MainIndexRoute
  '/admin': typeof AdminIndexRoute
  '/post/$id': typeof MainPostIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/admin/chronos/edit': typeof AdminChronosEditRoute
  '/admin/comics/create': typeof AdminComicsCreateRoute
  '/admin/emojis/create': typeof AdminEmojisCreateRoute
  '/admin/extras/featured': typeof AdminExtrasFeaturedRoute
  '/admin/extras/tutorials': typeof AdminExtrasTutorialsRoute
  '/admin/extras/weekly': typeof AdminExtrasWeeklyRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/stickers/create': typeof AdminStickersCreateRoute
  '/admin/terms/create': typeof AdminTermsCreateRoute
  '/admin/users/manage': typeof AdminUsersManageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/patreon/webhook': typeof ApiPatreonWebhookRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/comics': typeof AdminComicsIndexRoute
  '/admin/emojis': typeof AdminEmojisIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/stickers': typeof AdminStickersIndexRoute
  '/admin/terms': typeof AdminTermsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/post/reviews/$id': typeof MainPostReviewsIdRoute
  '/admin/comics/edit/$id': typeof AdminComicsEditIdRoute
  '/admin/emojis/$id/edit': typeof AdminEmojisIdEditRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
  '/admin/stickers/$id/edit': typeof AdminStickersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_main/about': typeof MainAboutRoute
  '/_main/chronos': typeof MainChronosRoute
  '/_main/forgot-password': typeof MainForgotPasswordRoute
  '/_main/legal': typeof MainLegalRoute
  '/_main/privacy': typeof MainPrivacyRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/reset-password': typeof MainResetPasswordRoute
  '/_main/search': typeof MainSearchRoute
  '/_main/terms': typeof MainTermsRoute
  '/_main/tutorials': typeof MainTutorialsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_main/post/$id': typeof MainPostIdRoute
  '/_main/user/$id': typeof MainUserIdRoute
  '/admin/chronos/edit': typeof AdminChronosEditRoute
  '/admin/comics/create': typeof AdminComicsCreateRoute
  '/admin/emojis/create': typeof AdminEmojisCreateRoute
  '/admin/extras/featured': typeof AdminExtrasFeaturedRoute
  '/admin/extras/tutorials': typeof AdminExtrasTutorialsRoute
  '/admin/extras/weekly': typeof AdminExtrasWeeklyRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/stickers/create': typeof AdminStickersCreateRoute
  '/admin/terms/create': typeof AdminTermsCreateRoute
  '/admin/users/manage': typeof AdminUsersManageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/patreon/webhook': typeof ApiPatreonWebhookRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/admin/comics/': typeof AdminComicsIndexRoute
  '/admin/emojis/': typeof AdminEmojisIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/stickers/': typeof AdminStickersIndexRoute
  '/admin/terms/': typeof AdminTermsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_main/post/reviews/$id': typeof MainPostReviewsIdRoute
  '/admin/comics/edit/$id': typeof AdminComicsEditIdRoute
  '/admin/emojis/$id/edit': typeof AdminEmojisIdEditRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
  '/admin/stickers/$id/edit': typeof AdminStickersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/about'
    | '/chronos'
    | '/forgot-password'
    | '/legal'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/tutorials'
    | '/admin/profile'
    | '/api/health'
    | '/admin/'
    | '/post/$id'
    | '/user/$id'
    | '/admin/chronos/edit'
    | '/admin/comics/create'
    | '/admin/emojis/create'
    | '/admin/extras/featured'
    | '/admin/extras/tutorials'
    | '/admin/extras/weekly'
    | '/admin/pages/$slug'
    | '/admin/posts/create'
    | '/admin/stickers/create'
    | '/admin/terms/create'
    | '/admin/users/manage'
    | '/api/auth/$'
    | '/api/patreon/webhook'
    | '/api/rpc/$'
    | '/admin/comics/'
    | '/admin/emojis/'
    | '/admin/posts/'
    | '/admin/stickers/'
    | '/admin/terms/'
    | '/admin/users/'
    | '/post/reviews/$id'
    | '/admin/comics/edit/$id'
    | '/admin/emojis/$id/edit'
    | '/admin/posts/edit/$id'
    | '/admin/stickers/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/chronos'
    | '/forgot-password'
    | '/legal'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/tutorials'
    | '/admin/profile'
    | '/api/health'
    | '/'
    | '/admin'
    | '/post/$id'
    | '/user/$id'
    | '/admin/chronos/edit'
    | '/admin/comics/create'
    | '/admin/emojis/create'
    | '/admin/extras/featured'
    | '/admin/extras/tutorials'
    | '/admin/extras/weekly'
    | '/admin/pages/$slug'
    | '/admin/posts/create'
    | '/admin/stickers/create'
    | '/admin/terms/create'
    | '/admin/users/manage'
    | '/api/auth/$'
    | '/api/patreon/webhook'
    | '/api/rpc/$'
    | '/admin/comics'
    | '/admin/emojis'
    | '/admin/posts'
    | '/admin/stickers'
    | '/admin/terms'
    | '/admin/users'
    | '/post/reviews/$id'
    | '/admin/comics/edit/$id'
    | '/admin/emojis/$id/edit'
    | '/admin/posts/edit/$id'
    | '/admin/stickers/$id/edit'
  id:
    | '__root__'
    | '/_main'
    | '/admin'
    | '/auth'
    | '/_main/about'
    | '/_main/chronos'
    | '/_main/forgot-password'
    | '/_main/legal'
    | '/_main/privacy'
    | '/_main/profile'
    | '/_main/reset-password'
    | '/_main/search'
    | '/_main/terms'
    | '/_main/tutorials'
    | '/admin/profile'
    | '/api/health'
    | '/_main/'
    | '/admin/'
    | '/_main/post/$id'
    | '/_main/user/$id'
    | '/admin/chronos/edit'
    | '/admin/comics/create'
    | '/admin/emojis/create'
    | '/admin/extras/featured'
    | '/admin/extras/tutorials'
    | '/admin/extras/weekly'
    | '/admin/pages/$slug'
    | '/admin/posts/create'
    | '/admin/stickers/create'
    | '/admin/terms/create'
    | '/admin/users/manage'
    | '/api/auth/$'
    | '/api/patreon/webhook'
    | '/api/rpc/$'
    | '/admin/comics/'
    | '/admin/emojis/'
    | '/admin/posts/'
    | '/admin/stickers/'
    | '/admin/terms/'
    | '/admin/users/'
    | '/_main/post/reviews/$id'
    | '/admin/comics/edit/$id'
    | '/admin/emojis/$id/edit'
    | '/admin/posts/edit/$id'
    | '/admin/stickers/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPatreonWebhookRoute: typeof ApiPatreonWebhookRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/tutorials': {
      id: '/_main/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof MainTutorialsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/terms': {
      id: '/_main/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainTermsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reset-password': {
      id: '/_main/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainResetPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/privacy': {
      id: '/_main/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainPrivacyRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/legal': {
      id: '/_main/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof MainLegalRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/forgot-password': {
      id: '/_main/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof MainForgotPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/chronos': {
      id: '/_main/chronos'
      path: '/chronos'
      fullPath: '/chronos'
      preLoaderRoute: typeof MainChronosRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/terms/': {
      id: '/admin/terms/'
      path: '/terms'
      fullPath: '/admin/terms/'
      preLoaderRoute: typeof AdminTermsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stickers/': {
      id: '/admin/stickers/'
      path: '/stickers'
      fullPath: '/admin/stickers/'
      preLoaderRoute: typeof AdminStickersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emojis/': {
      id: '/admin/emojis/'
      path: '/emojis'
      fullPath: '/admin/emojis/'
      preLoaderRoute: typeof AdminEmojisIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comics/': {
      id: '/admin/comics/'
      path: '/comics'
      fullPath: '/admin/comics/'
      preLoaderRoute: typeof AdminComicsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patreon/webhook': {
      id: '/api/patreon/webhook'
      path: '/api/patreon/webhook'
      fullPath: '/api/patreon/webhook'
      preLoaderRoute: typeof ApiPatreonWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/manage': {
      id: '/admin/users/manage'
      path: '/users/manage'
      fullPath: '/admin/users/manage'
      preLoaderRoute: typeof AdminUsersManageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/terms/create': {
      id: '/admin/terms/create'
      path: '/terms/create'
      fullPath: '/admin/terms/create'
      preLoaderRoute: typeof AdminTermsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stickers/create': {
      id: '/admin/stickers/create'
      path: '/stickers/create'
      fullPath: '/admin/stickers/create'
      preLoaderRoute: typeof AdminStickersCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/posts/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/$slug': {
      id: '/admin/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/admin/pages/$slug'
      preLoaderRoute: typeof AdminPagesSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extras/weekly': {
      id: '/admin/extras/weekly'
      path: '/extras/weekly'
      fullPath: '/admin/extras/weekly'
      preLoaderRoute: typeof AdminExtrasWeeklyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extras/tutorials': {
      id: '/admin/extras/tutorials'
      path: '/extras/tutorials'
      fullPath: '/admin/extras/tutorials'
      preLoaderRoute: typeof AdminExtrasTutorialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extras/featured': {
      id: '/admin/extras/featured'
      path: '/extras/featured'
      fullPath: '/admin/extras/featured'
      preLoaderRoute: typeof AdminExtrasFeaturedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emojis/create': {
      id: '/admin/emojis/create'
      path: '/emojis/create'
      fullPath: '/admin/emojis/create'
      preLoaderRoute: typeof AdminEmojisCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comics/create': {
      id: '/admin/comics/create'
      path: '/comics/create'
      fullPath: '/admin/comics/create'
      preLoaderRoute: typeof AdminComicsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chronos/edit': {
      id: '/admin/chronos/edit'
      path: '/chronos/edit'
      fullPath: '/admin/chronos/edit'
      preLoaderRoute: typeof AdminChronosEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/user/$id': {
      id: '/_main/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof MainUserIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/post/$id': {
      id: '/_main/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof MainPostIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/admin/stickers/$id/edit': {
      id: '/admin/stickers/$id/edit'
      path: '/stickers/$id/edit'
      fullPath: '/admin/stickers/$id/edit'
      preLoaderRoute: typeof AdminStickersIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/posts/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emojis/$id/edit': {
      id: '/admin/emojis/$id/edit'
      path: '/emojis/$id/edit'
      fullPath: '/admin/emojis/$id/edit'
      preLoaderRoute: typeof AdminEmojisIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comics/edit/$id': {
      id: '/admin/comics/edit/$id'
      path: '/comics/edit/$id'
      fullPath: '/admin/comics/edit/$id'
      preLoaderRoute: typeof AdminComicsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/post/reviews/$id': {
      id: '/_main/post/reviews/$id'
      path: '/post/reviews/$id'
      fullPath: '/post/reviews/$id'
      preLoaderRoute: typeof MainPostReviewsIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainChronosRoute: typeof MainChronosRoute
  MainForgotPasswordRoute: typeof MainForgotPasswordRoute
  MainLegalRoute: typeof MainLegalRoute
  MainPrivacyRoute: typeof MainPrivacyRoute
  MainProfileRoute: typeof MainProfileRoute
  MainResetPasswordRoute: typeof MainResetPasswordRoute
  MainSearchRoute: typeof MainSearchRoute
  MainTermsRoute: typeof MainTermsRoute
  MainTutorialsRoute: typeof MainTutorialsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainPostIdRoute: typeof MainPostIdRoute
  MainUserIdRoute: typeof MainUserIdRoute
  MainPostReviewsIdRoute: typeof MainPostReviewsIdRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainChronosRoute: MainChronosRoute,
  MainForgotPasswordRoute: MainForgotPasswordRoute,
  MainLegalRoute: MainLegalRoute,
  MainPrivacyRoute: MainPrivacyRoute,
  MainProfileRoute: MainProfileRoute,
  MainResetPasswordRoute: MainResetPasswordRoute,
  MainSearchRoute: MainSearchRoute,
  MainTermsRoute: MainTermsRoute,
  MainTutorialsRoute: MainTutorialsRoute,
  MainIndexRoute: MainIndexRoute,
  MainPostIdRoute: MainPostIdRoute,
  MainUserIdRoute: MainUserIdRoute,
  MainPostReviewsIdRoute: MainPostReviewsIdRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminProfileRoute: typeof AdminProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChronosEditRoute: typeof AdminChronosEditRoute
  AdminComicsCreateRoute: typeof AdminComicsCreateRoute
  AdminEmojisCreateRoute: typeof AdminEmojisCreateRoute
  AdminExtrasFeaturedRoute: typeof AdminExtrasFeaturedRoute
  AdminExtrasTutorialsRoute: typeof AdminExtrasTutorialsRoute
  AdminExtrasWeeklyRoute: typeof AdminExtrasWeeklyRoute
  AdminPagesSlugRoute: typeof AdminPagesSlugRoute
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminStickersCreateRoute: typeof AdminStickersCreateRoute
  AdminTermsCreateRoute: typeof AdminTermsCreateRoute
  AdminUsersManageRoute: typeof AdminUsersManageRoute
  AdminComicsIndexRoute: typeof AdminComicsIndexRoute
  AdminEmojisIndexRoute: typeof AdminEmojisIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminStickersIndexRoute: typeof AdminStickersIndexRoute
  AdminTermsIndexRoute: typeof AdminTermsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminComicsEditIdRoute: typeof AdminComicsEditIdRoute
  AdminEmojisIdEditRoute: typeof AdminEmojisIdEditRoute
  AdminPostsEditIdRoute: typeof AdminPostsEditIdRoute
  AdminStickersIdEditRoute: typeof AdminStickersIdEditRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminProfileRoute: AdminProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminChronosEditRoute: AdminChronosEditRoute,
  AdminComicsCreateRoute: AdminComicsCreateRoute,
  AdminEmojisCreateRoute: AdminEmojisCreateRoute,
  AdminExtrasFeaturedRoute: AdminExtrasFeaturedRoute,
  AdminExtrasTutorialsRoute: AdminExtrasTutorialsRoute,
  AdminExtrasWeeklyRoute: AdminExtrasWeeklyRoute,
  AdminPagesSlugRoute: AdminPagesSlugRoute,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminStickersCreateRoute: AdminStickersCreateRoute,
  AdminTermsCreateRoute: AdminTermsCreateRoute,
  AdminUsersManageRoute: AdminUsersManageRoute,
  AdminComicsIndexRoute: AdminComicsIndexRoute,
  AdminEmojisIndexRoute: AdminEmojisIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminStickersIndexRoute: AdminStickersIndexRoute,
  AdminTermsIndexRoute: AdminTermsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminComicsEditIdRoute: AdminComicsEditIdRoute,
  AdminEmojisIdEditRoute: AdminEmojisIdEditRoute,
  AdminPostsEditIdRoute: AdminPostsEditIdRoute,
  AdminStickersIdEditRoute: AdminStickersIdEditRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPatreonWebhookRoute: ApiPatreonWebhookRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
