/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as DemoNRouteImport } from './routes/demo/n'
import { Route as DemoMRouteImport } from './routes/demo/m'
import { Route as DemoLRouteImport } from './routes/demo/l'
import { Route as DemoKRouteImport } from './routes/demo/k'
import { Route as DemoJRouteImport } from './routes/demo/j'
import { Route as DemoIRouteImport } from './routes/demo/i'
import { Route as DemoHRouteImport } from './routes/demo/h'
import { Route as DemoGRouteImport } from './routes/demo/g'
import { Route as DemoFRouteImport } from './routes/demo/f'
import { Route as DemoERouteImport } from './routes/demo/e'
import { Route as DemoDRouteImport } from './routes/demo/d'
import { Route as DemoCRouteImport } from './routes/demo/c'
import { Route as DemoBRouteImport } from './routes/demo/b'
import { Route as DemoARouteImport } from './routes/demo/a'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as MainVipRouteImport } from './routes/_main/vip'
import { Route as MainTutorialsRouteImport } from './routes/_main/tutorials'
import { Route as MainTermsRouteImport } from './routes/_main/terms'
import { Route as MainSearchRouteImport } from './routes/_main/search'
import { Route as MainResetPasswordRouteImport } from './routes/_main/reset-password'
import { Route as MainProfileRouteImport } from './routes/_main/profile'
import { Route as MainPrivacyRouteImport } from './routes/_main/privacy'
import { Route as MainLegalRouteImport } from './routes/_main/legal'
import { Route as MainJuegosRouteImport } from './routes/_main/juegos'
import { Route as MainForgotPasswordRouteImport } from './routes/_main/forgot-password'
import { Route as MainComicsRouteImport } from './routes/_main/comics'
import { Route as MainChronosRouteImport } from './routes/_main/chronos'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTermsIndexRouteImport } from './routes/admin/terms/index'
import { Route as AdminStickersIndexRouteImport } from './routes/admin/stickers/index'
import { Route as AdminProfileIndexRouteImport } from './routes/admin/profile/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminNotificationsIndexRouteImport } from './routes/admin/notifications/index'
import { Route as AdminMediaIndexRouteImport } from './routes/admin/media/index'
import { Route as AdminEmojisIndexRouteImport } from './routes/admin/emojis/index'
import { Route as AdminCreatorsIndexRouteImport } from './routes/admin/creators/index'
import { Route as AdminComicsIndexRouteImport } from './routes/admin/comics/index'
import { Route as MainNewsIndexRouteImport } from './routes/_main/news.index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiPatreonWebhookRouteImport } from './routes/api/patreon/webhook'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AdminUsersManageRouteImport } from './routes/admin/users/manage'
import { Route as AdminTermsCreateRouteImport } from './routes/admin/terms/create'
import { Route as AdminStickersCreateRouteImport } from './routes/admin/stickers/create'
import { Route as AdminSiteMarqueeRouteImport } from './routes/admin/site/marquee'
import { Route as AdminProfileRolesRouteImport } from './routes/admin/profile/roles'
import { Route as AdminProfileEmblemsRouteImport } from './routes/admin/profile/emblems'
import { Route as AdminPostsCreateRouteImport } from './routes/admin/posts/create'
import { Route as AdminPagesSlugRouteImport } from './routes/admin/pages/$slug'
import { Route as AdminExtrasWeeklyRouteImport } from './routes/admin/extras/weekly'
import { Route as AdminExtrasTutorialsRouteImport } from './routes/admin/extras/tutorials'
import { Route as AdminExtrasFeaturedRouteImport } from './routes/admin/extras/featured'
import { Route as AdminExtrasEngagementRouteImport } from './routes/admin/extras/engagement'
import { Route as AdminEmojisCreateRouteImport } from './routes/admin/emojis/create'
import { Route as AdminComicsCreateRouteImport } from './routes/admin/comics/create'
import { Route as AdminChronosEditRouteImport } from './routes/admin/chronos/edit'
import { Route as MainUserIdRouteImport } from './routes/_main/user.$id'
import { Route as MainPostIdRouteImport } from './routes/_main/post.$id'
import { Route as MainNewsIdRouteImport } from './routes/_main/news.$id'
import { Route as AdminNotificationsArticlesIndexRouteImport } from './routes/admin/notifications/articles/index'
import { Route as AdminNotificationsAnnouncementsIndexRouteImport } from './routes/admin/notifications/announcements/index'
import { Route as AdminStickersIdEditRouteImport } from './routes/admin/stickers/$id.edit'
import { Route as AdminPostsEditIdRouteImport } from './routes/admin/posts/edit.$id'
import { Route as AdminNotificationsArticlesCreateRouteImport } from './routes/admin/notifications/articles/create'
import { Route as AdminNotificationsAnnouncementsCreateRouteImport } from './routes/admin/notifications/announcements/create'
import { Route as AdminEmojisIdEditRouteImport } from './routes/admin/emojis/$id.edit'
import { Route as AdminComicsEditIdRouteImport } from './routes/admin/comics/edit.$id'
import { Route as MainPostReviewsIdRouteImport } from './routes/_main/post.reviews.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const DemoNRoute = DemoNRouteImport.update({
  id: '/demo/n',
  path: '/demo/n',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMRoute = DemoMRouteImport.update({
  id: '/demo/m',
  path: '/demo/m',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLRoute = DemoLRouteImport.update({
  id: '/demo/l',
  path: '/demo/l',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoKRoute = DemoKRouteImport.update({
  id: '/demo/k',
  path: '/demo/k',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoJRoute = DemoJRouteImport.update({
  id: '/demo/j',
  path: '/demo/j',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIRoute = DemoIRouteImport.update({
  id: '/demo/i',
  path: '/demo/i',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoHRoute = DemoHRouteImport.update({
  id: '/demo/h',
  path: '/demo/h',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGRoute = DemoGRouteImport.update({
  id: '/demo/g',
  path: '/demo/g',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFRoute = DemoFRouteImport.update({
  id: '/demo/f',
  path: '/demo/f',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoERoute = DemoERouteImport.update({
  id: '/demo/e',
  path: '/demo/e',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDRoute = DemoDRouteImport.update({
  id: '/demo/d',
  path: '/demo/d',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCRoute = DemoCRouteImport.update({
  id: '/demo/c',
  path: '/demo/c',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBRoute = DemoBRouteImport.update({
  id: '/demo/b',
  path: '/demo/b',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoARoute = DemoARouteImport.update({
  id: '/demo/a',
  path: '/demo/a',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const MainVipRoute = MainVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTutorialsRoute = MainTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTermsRoute = MainTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSearchRoute = MainSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainResetPasswordRoute = MainResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPrivacyRoute = MainPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLegalRoute = MainLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainJuegosRoute = MainJuegosRouteImport.update({
  id: '/juegos',
  path: '/juegos',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainForgotPasswordRoute = MainForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainComicsRoute = MainComicsRouteImport.update({
  id: '/comics',
  path: '/comics',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainChronosRoute = MainChronosRouteImport.update({
  id: '/chronos',
  path: '/chronos',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTermsIndexRoute = AdminTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStickersIndexRoute = AdminStickersIndexRouteImport.update({
  id: '/stickers/',
  path: '/stickers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileIndexRoute = AdminProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsIndexRoute = AdminNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMediaIndexRoute = AdminMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmojisIndexRoute = AdminEmojisIndexRouteImport.update({
  id: '/emojis/',
  path: '/emojis/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreatorsIndexRoute = AdminCreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComicsIndexRoute = AdminComicsIndexRouteImport.update({
  id: '/comics/',
  path: '/comics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainNewsIndexRoute = MainNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPatreonWebhookRoute = ApiPatreonWebhookRouteImport.update({
  id: '/api/patreon/webhook',
  path: '/api/patreon/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersManageRoute = AdminUsersManageRouteImport.update({
  id: '/users/manage',
  path: '/users/manage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTermsCreateRoute = AdminTermsCreateRouteImport.update({
  id: '/terms/create',
  path: '/terms/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStickersCreateRoute = AdminStickersCreateRouteImport.update({
  id: '/stickers/create',
  path: '/stickers/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSiteMarqueeRoute = AdminSiteMarqueeRouteImport.update({
  id: '/site/marquee',
  path: '/site/marquee',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileRolesRoute = AdminProfileRolesRouteImport.update({
  id: '/profile/roles',
  path: '/profile/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProfileEmblemsRoute = AdminProfileEmblemsRouteImport.update({
  id: '/profile/emblems',
  path: '/profile/emblems',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsCreateRoute = AdminPostsCreateRouteImport.update({
  id: '/posts/create',
  path: '/posts/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPagesSlugRoute = AdminPagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtrasWeeklyRoute = AdminExtrasWeeklyRouteImport.update({
  id: '/extras/weekly',
  path: '/extras/weekly',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtrasTutorialsRoute = AdminExtrasTutorialsRouteImport.update({
  id: '/extras/tutorials',
  path: '/extras/tutorials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtrasFeaturedRoute = AdminExtrasFeaturedRouteImport.update({
  id: '/extras/featured',
  path: '/extras/featured',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminExtrasEngagementRoute = AdminExtrasEngagementRouteImport.update({
  id: '/extras/engagement',
  path: '/extras/engagement',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmojisCreateRoute = AdminEmojisCreateRouteImport.update({
  id: '/emojis/create',
  path: '/emojis/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComicsCreateRoute = AdminComicsCreateRouteImport.update({
  id: '/comics/create',
  path: '/comics/create',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminChronosEditRoute = AdminChronosEditRouteImport.update({
  id: '/chronos/edit',
  path: '/chronos/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainUserIdRoute = MainUserIdRouteImport.update({
  id: '/user/$id',
  path: '/user/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPostIdRoute = MainPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainNewsIdRoute = MainNewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const AdminNotificationsArticlesIndexRoute =
  AdminNotificationsArticlesIndexRouteImport.update({
    id: '/notifications/articles/',
    path: '/notifications/articles/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminNotificationsAnnouncementsIndexRoute =
  AdminNotificationsAnnouncementsIndexRouteImport.update({
    id: '/notifications/announcements/',
    path: '/notifications/announcements/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminStickersIdEditRoute = AdminStickersIdEditRouteImport.update({
  id: '/stickers/$id/edit',
  path: '/stickers/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsEditIdRoute = AdminPostsEditIdRouteImport.update({
  id: '/posts/edit/$id',
  path: '/posts/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsArticlesCreateRoute =
  AdminNotificationsArticlesCreateRouteImport.update({
    id: '/notifications/articles/create',
    path: '/notifications/articles/create',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminNotificationsAnnouncementsCreateRoute =
  AdminNotificationsAnnouncementsCreateRouteImport.update({
    id: '/notifications/announcements/create',
    path: '/notifications/announcements/create',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminEmojisIdEditRoute = AdminEmojisIdEditRouteImport.update({
  id: '/emojis/$id/edit',
  path: '/emojis/$id/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComicsEditIdRoute = AdminComicsEditIdRouteImport.update({
  id: '/comics/edit/$id',
  path: '/comics/edit/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MainPostReviewsIdRoute = MainPostReviewsIdRouteImport.update({
  id: '/post/reviews/$id',
  path: '/post/reviews/$id',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/about': typeof MainAboutRoute
  '/chronos': typeof MainChronosRoute
  '/comics': typeof MainComicsRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/juegos': typeof MainJuegosRoute
  '/legal': typeof MainLegalRoute
  '/privacy': typeof MainPrivacyRoute
  '/profile': typeof MainProfileRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/search': typeof MainSearchRoute
  '/terms': typeof MainTermsRoute
  '/tutorials': typeof MainTutorialsRoute
  '/vip': typeof MainVipRoute
  '/api/health': typeof ApiHealthRoute
  '/demo/a': typeof DemoARoute
  '/demo/b': typeof DemoBRoute
  '/demo/c': typeof DemoCRoute
  '/demo/d': typeof DemoDRoute
  '/demo/e': typeof DemoERoute
  '/demo/f': typeof DemoFRoute
  '/demo/g': typeof DemoGRoute
  '/demo/h': typeof DemoHRoute
  '/demo/i': typeof DemoIRoute
  '/demo/j': typeof DemoJRoute
  '/demo/k': typeof DemoKRoute
  '/demo/l': typeof DemoLRoute
  '/demo/m': typeof DemoMRoute
  '/demo/n': typeof DemoNRoute
  '/admin/': typeof AdminIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/news/$id': typeof MainNewsIdRoute
  '/post/$id': typeof MainPostIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/admin/chronos/edit': typeof AdminChronosEditRoute
  '/admin/comics/create': typeof AdminComicsCreateRoute
  '/admin/emojis/create': typeof AdminEmojisCreateRoute
  '/admin/extras/engagement': typeof AdminExtrasEngagementRoute
  '/admin/extras/featured': typeof AdminExtrasFeaturedRoute
  '/admin/extras/tutorials': typeof AdminExtrasTutorialsRoute
  '/admin/extras/weekly': typeof AdminExtrasWeeklyRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/profile/emblems': typeof AdminProfileEmblemsRoute
  '/admin/profile/roles': typeof AdminProfileRolesRoute
  '/admin/site/marquee': typeof AdminSiteMarqueeRoute
  '/admin/stickers/create': typeof AdminStickersCreateRoute
  '/admin/terms/create': typeof AdminTermsCreateRoute
  '/admin/users/manage': typeof AdminUsersManageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/patreon/webhook': typeof ApiPatreonWebhookRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/news/': typeof MainNewsIndexRoute
  '/admin/comics/': typeof AdminComicsIndexRoute
  '/admin/creators/': typeof AdminCreatorsIndexRoute
  '/admin/emojis/': typeof AdminEmojisIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/stickers/': typeof AdminStickersIndexRoute
  '/admin/terms/': typeof AdminTermsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/post/reviews/$id': typeof MainPostReviewsIdRoute
  '/admin/comics/edit/$id': typeof AdminComicsEditIdRoute
  '/admin/emojis/$id/edit': typeof AdminEmojisIdEditRoute
  '/admin/notifications/announcements/create': typeof AdminNotificationsAnnouncementsCreateRoute
  '/admin/notifications/articles/create': typeof AdminNotificationsArticlesCreateRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
  '/admin/stickers/$id/edit': typeof AdminStickersIdEditRoute
  '/admin/notifications/announcements/': typeof AdminNotificationsAnnouncementsIndexRoute
  '/admin/notifications/articles/': typeof AdminNotificationsArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/about': typeof MainAboutRoute
  '/chronos': typeof MainChronosRoute
  '/comics': typeof MainComicsRoute
  '/forgot-password': typeof MainForgotPasswordRoute
  '/juegos': typeof MainJuegosRoute
  '/legal': typeof MainLegalRoute
  '/privacy': typeof MainPrivacyRoute
  '/profile': typeof MainProfileRoute
  '/reset-password': typeof MainResetPasswordRoute
  '/search': typeof MainSearchRoute
  '/terms': typeof MainTermsRoute
  '/tutorials': typeof MainTutorialsRoute
  '/vip': typeof MainVipRoute
  '/api/health': typeof ApiHealthRoute
  '/demo/a': typeof DemoARoute
  '/demo/b': typeof DemoBRoute
  '/demo/c': typeof DemoCRoute
  '/demo/d': typeof DemoDRoute
  '/demo/e': typeof DemoERoute
  '/demo/f': typeof DemoFRoute
  '/demo/g': typeof DemoGRoute
  '/demo/h': typeof DemoHRoute
  '/demo/i': typeof DemoIRoute
  '/demo/j': typeof DemoJRoute
  '/demo/k': typeof DemoKRoute
  '/demo/l': typeof DemoLRoute
  '/demo/m': typeof DemoMRoute
  '/demo/n': typeof DemoNRoute
  '/': typeof MainIndexRoute
  '/admin': typeof AdminIndexRoute
  '/demo': typeof DemoIndexRoute
  '/news/$id': typeof MainNewsIdRoute
  '/post/$id': typeof MainPostIdRoute
  '/user/$id': typeof MainUserIdRoute
  '/admin/chronos/edit': typeof AdminChronosEditRoute
  '/admin/comics/create': typeof AdminComicsCreateRoute
  '/admin/emojis/create': typeof AdminEmojisCreateRoute
  '/admin/extras/engagement': typeof AdminExtrasEngagementRoute
  '/admin/extras/featured': typeof AdminExtrasFeaturedRoute
  '/admin/extras/tutorials': typeof AdminExtrasTutorialsRoute
  '/admin/extras/weekly': typeof AdminExtrasWeeklyRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/profile/emblems': typeof AdminProfileEmblemsRoute
  '/admin/profile/roles': typeof AdminProfileRolesRoute
  '/admin/site/marquee': typeof AdminSiteMarqueeRoute
  '/admin/stickers/create': typeof AdminStickersCreateRoute
  '/admin/terms/create': typeof AdminTermsCreateRoute
  '/admin/users/manage': typeof AdminUsersManageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/patreon/webhook': typeof ApiPatreonWebhookRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/news': typeof MainNewsIndexRoute
  '/admin/comics': typeof AdminComicsIndexRoute
  '/admin/creators': typeof AdminCreatorsIndexRoute
  '/admin/emojis': typeof AdminEmojisIndexRoute
  '/admin/media': typeof AdminMediaIndexRoute
  '/admin/notifications': typeof AdminNotificationsIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/profile': typeof AdminProfileIndexRoute
  '/admin/stickers': typeof AdminStickersIndexRoute
  '/admin/terms': typeof AdminTermsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/post/reviews/$id': typeof MainPostReviewsIdRoute
  '/admin/comics/edit/$id': typeof AdminComicsEditIdRoute
  '/admin/emojis/$id/edit': typeof AdminEmojisIdEditRoute
  '/admin/notifications/announcements/create': typeof AdminNotificationsAnnouncementsCreateRoute
  '/admin/notifications/articles/create': typeof AdminNotificationsArticlesCreateRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
  '/admin/stickers/$id/edit': typeof AdminStickersIdEditRoute
  '/admin/notifications/announcements': typeof AdminNotificationsAnnouncementsIndexRoute
  '/admin/notifications/articles': typeof AdminNotificationsArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_main/about': typeof MainAboutRoute
  '/_main/chronos': typeof MainChronosRoute
  '/_main/comics': typeof MainComicsRoute
  '/_main/forgot-password': typeof MainForgotPasswordRoute
  '/_main/juegos': typeof MainJuegosRoute
  '/_main/legal': typeof MainLegalRoute
  '/_main/privacy': typeof MainPrivacyRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/reset-password': typeof MainResetPasswordRoute
  '/_main/search': typeof MainSearchRoute
  '/_main/terms': typeof MainTermsRoute
  '/_main/tutorials': typeof MainTutorialsRoute
  '/_main/vip': typeof MainVipRoute
  '/api/health': typeof ApiHealthRoute
  '/demo/a': typeof DemoARoute
  '/demo/b': typeof DemoBRoute
  '/demo/c': typeof DemoCRoute
  '/demo/d': typeof DemoDRoute
  '/demo/e': typeof DemoERoute
  '/demo/f': typeof DemoFRoute
  '/demo/g': typeof DemoGRoute
  '/demo/h': typeof DemoHRoute
  '/demo/i': typeof DemoIRoute
  '/demo/j': typeof DemoJRoute
  '/demo/k': typeof DemoKRoute
  '/demo/l': typeof DemoLRoute
  '/demo/m': typeof DemoMRoute
  '/demo/n': typeof DemoNRoute
  '/_main/': typeof MainIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/_main/news/$id': typeof MainNewsIdRoute
  '/_main/post/$id': typeof MainPostIdRoute
  '/_main/user/$id': typeof MainUserIdRoute
  '/admin/chronos/edit': typeof AdminChronosEditRoute
  '/admin/comics/create': typeof AdminComicsCreateRoute
  '/admin/emojis/create': typeof AdminEmojisCreateRoute
  '/admin/extras/engagement': typeof AdminExtrasEngagementRoute
  '/admin/extras/featured': typeof AdminExtrasFeaturedRoute
  '/admin/extras/tutorials': typeof AdminExtrasTutorialsRoute
  '/admin/extras/weekly': typeof AdminExtrasWeeklyRoute
  '/admin/pages/$slug': typeof AdminPagesSlugRoute
  '/admin/posts/create': typeof AdminPostsCreateRoute
  '/admin/profile/emblems': typeof AdminProfileEmblemsRoute
  '/admin/profile/roles': typeof AdminProfileRolesRoute
  '/admin/site/marquee': typeof AdminSiteMarqueeRoute
  '/admin/stickers/create': typeof AdminStickersCreateRoute
  '/admin/terms/create': typeof AdminTermsCreateRoute
  '/admin/users/manage': typeof AdminUsersManageRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/patreon/webhook': typeof ApiPatreonWebhookRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_main/news/': typeof MainNewsIndexRoute
  '/admin/comics/': typeof AdminComicsIndexRoute
  '/admin/creators/': typeof AdminCreatorsIndexRoute
  '/admin/emojis/': typeof AdminEmojisIndexRoute
  '/admin/media/': typeof AdminMediaIndexRoute
  '/admin/notifications/': typeof AdminNotificationsIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/profile/': typeof AdminProfileIndexRoute
  '/admin/stickers/': typeof AdminStickersIndexRoute
  '/admin/terms/': typeof AdminTermsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_main/post/reviews/$id': typeof MainPostReviewsIdRoute
  '/admin/comics/edit/$id': typeof AdminComicsEditIdRoute
  '/admin/emojis/$id/edit': typeof AdminEmojisIdEditRoute
  '/admin/notifications/announcements/create': typeof AdminNotificationsAnnouncementsCreateRoute
  '/admin/notifications/articles/create': typeof AdminNotificationsArticlesCreateRoute
  '/admin/posts/edit/$id': typeof AdminPostsEditIdRoute
  '/admin/stickers/$id/edit': typeof AdminStickersIdEditRoute
  '/admin/notifications/announcements/': typeof AdminNotificationsAnnouncementsIndexRoute
  '/admin/notifications/articles/': typeof AdminNotificationsArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/about'
    | '/chronos'
    | '/comics'
    | '/forgot-password'
    | '/juegos'
    | '/legal'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/tutorials'
    | '/vip'
    | '/api/health'
    | '/demo/a'
    | '/demo/b'
    | '/demo/c'
    | '/demo/d'
    | '/demo/e'
    | '/demo/f'
    | '/demo/g'
    | '/demo/h'
    | '/demo/i'
    | '/demo/j'
    | '/demo/k'
    | '/demo/l'
    | '/demo/m'
    | '/demo/n'
    | '/admin/'
    | '/demo/'
    | '/news/$id'
    | '/post/$id'
    | '/user/$id'
    | '/admin/chronos/edit'
    | '/admin/comics/create'
    | '/admin/emojis/create'
    | '/admin/extras/engagement'
    | '/admin/extras/featured'
    | '/admin/extras/tutorials'
    | '/admin/extras/weekly'
    | '/admin/pages/$slug'
    | '/admin/posts/create'
    | '/admin/profile/emblems'
    | '/admin/profile/roles'
    | '/admin/site/marquee'
    | '/admin/stickers/create'
    | '/admin/terms/create'
    | '/admin/users/manage'
    | '/api/auth/$'
    | '/api/patreon/webhook'
    | '/api/rpc/$'
    | '/news/'
    | '/admin/comics/'
    | '/admin/creators/'
    | '/admin/emojis/'
    | '/admin/media/'
    | '/admin/notifications/'
    | '/admin/posts/'
    | '/admin/profile/'
    | '/admin/stickers/'
    | '/admin/terms/'
    | '/admin/users/'
    | '/post/reviews/$id'
    | '/admin/comics/edit/$id'
    | '/admin/emojis/$id/edit'
    | '/admin/notifications/announcements/create'
    | '/admin/notifications/articles/create'
    | '/admin/posts/edit/$id'
    | '/admin/stickers/$id/edit'
    | '/admin/notifications/announcements/'
    | '/admin/notifications/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/about'
    | '/chronos'
    | '/comics'
    | '/forgot-password'
    | '/juegos'
    | '/legal'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/tutorials'
    | '/vip'
    | '/api/health'
    | '/demo/a'
    | '/demo/b'
    | '/demo/c'
    | '/demo/d'
    | '/demo/e'
    | '/demo/f'
    | '/demo/g'
    | '/demo/h'
    | '/demo/i'
    | '/demo/j'
    | '/demo/k'
    | '/demo/l'
    | '/demo/m'
    | '/demo/n'
    | '/'
    | '/admin'
    | '/demo'
    | '/news/$id'
    | '/post/$id'
    | '/user/$id'
    | '/admin/chronos/edit'
    | '/admin/comics/create'
    | '/admin/emojis/create'
    | '/admin/extras/engagement'
    | '/admin/extras/featured'
    | '/admin/extras/tutorials'
    | '/admin/extras/weekly'
    | '/admin/pages/$slug'
    | '/admin/posts/create'
    | '/admin/profile/emblems'
    | '/admin/profile/roles'
    | '/admin/site/marquee'
    | '/admin/stickers/create'
    | '/admin/terms/create'
    | '/admin/users/manage'
    | '/api/auth/$'
    | '/api/patreon/webhook'
    | '/api/rpc/$'
    | '/news'
    | '/admin/comics'
    | '/admin/creators'
    | '/admin/emojis'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/posts'
    | '/admin/profile'
    | '/admin/stickers'
    | '/admin/terms'
    | '/admin/users'
    | '/post/reviews/$id'
    | '/admin/comics/edit/$id'
    | '/admin/emojis/$id/edit'
    | '/admin/notifications/announcements/create'
    | '/admin/notifications/articles/create'
    | '/admin/posts/edit/$id'
    | '/admin/stickers/$id/edit'
    | '/admin/notifications/announcements'
    | '/admin/notifications/articles'
  id:
    | '__root__'
    | '/_main'
    | '/admin'
    | '/auth'
    | '/_main/about'
    | '/_main/chronos'
    | '/_main/comics'
    | '/_main/forgot-password'
    | '/_main/juegos'
    | '/_main/legal'
    | '/_main/privacy'
    | '/_main/profile'
    | '/_main/reset-password'
    | '/_main/search'
    | '/_main/terms'
    | '/_main/tutorials'
    | '/_main/vip'
    | '/api/health'
    | '/demo/a'
    | '/demo/b'
    | '/demo/c'
    | '/demo/d'
    | '/demo/e'
    | '/demo/f'
    | '/demo/g'
    | '/demo/h'
    | '/demo/i'
    | '/demo/j'
    | '/demo/k'
    | '/demo/l'
    | '/demo/m'
    | '/demo/n'
    | '/_main/'
    | '/admin/'
    | '/demo/'
    | '/_main/news/$id'
    | '/_main/post/$id'
    | '/_main/user/$id'
    | '/admin/chronos/edit'
    | '/admin/comics/create'
    | '/admin/emojis/create'
    | '/admin/extras/engagement'
    | '/admin/extras/featured'
    | '/admin/extras/tutorials'
    | '/admin/extras/weekly'
    | '/admin/pages/$slug'
    | '/admin/posts/create'
    | '/admin/profile/emblems'
    | '/admin/profile/roles'
    | '/admin/site/marquee'
    | '/admin/stickers/create'
    | '/admin/terms/create'
    | '/admin/users/manage'
    | '/api/auth/$'
    | '/api/patreon/webhook'
    | '/api/rpc/$'
    | '/_main/news/'
    | '/admin/comics/'
    | '/admin/creators/'
    | '/admin/emojis/'
    | '/admin/media/'
    | '/admin/notifications/'
    | '/admin/posts/'
    | '/admin/profile/'
    | '/admin/stickers/'
    | '/admin/terms/'
    | '/admin/users/'
    | '/_main/post/reviews/$id'
    | '/admin/comics/edit/$id'
    | '/admin/emojis/$id/edit'
    | '/admin/notifications/announcements/create'
    | '/admin/notifications/articles/create'
    | '/admin/posts/edit/$id'
    | '/admin/stickers/$id/edit'
    | '/admin/notifications/announcements/'
    | '/admin/notifications/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DemoARoute: typeof DemoARoute
  DemoBRoute: typeof DemoBRoute
  DemoCRoute: typeof DemoCRoute
  DemoDRoute: typeof DemoDRoute
  DemoERoute: typeof DemoERoute
  DemoFRoute: typeof DemoFRoute
  DemoGRoute: typeof DemoGRoute
  DemoHRoute: typeof DemoHRoute
  DemoIRoute: typeof DemoIRoute
  DemoJRoute: typeof DemoJRoute
  DemoKRoute: typeof DemoKRoute
  DemoLRoute: typeof DemoLRoute
  DemoMRoute: typeof DemoMRoute
  DemoNRoute: typeof DemoNRoute
  DemoIndexRoute: typeof DemoIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPatreonWebhookRoute: typeof ApiPatreonWebhookRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/demo/n': {
      id: '/demo/n'
      path: '/demo/n'
      fullPath: '/demo/n'
      preLoaderRoute: typeof DemoNRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/m': {
      id: '/demo/m'
      path: '/demo/m'
      fullPath: '/demo/m'
      preLoaderRoute: typeof DemoMRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/l': {
      id: '/demo/l'
      path: '/demo/l'
      fullPath: '/demo/l'
      preLoaderRoute: typeof DemoLRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/k': {
      id: '/demo/k'
      path: '/demo/k'
      fullPath: '/demo/k'
      preLoaderRoute: typeof DemoKRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/j': {
      id: '/demo/j'
      path: '/demo/j'
      fullPath: '/demo/j'
      preLoaderRoute: typeof DemoJRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i': {
      id: '/demo/i'
      path: '/demo/i'
      fullPath: '/demo/i'
      preLoaderRoute: typeof DemoIRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/h': {
      id: '/demo/h'
      path: '/demo/h'
      fullPath: '/demo/h'
      preLoaderRoute: typeof DemoHRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/g': {
      id: '/demo/g'
      path: '/demo/g'
      fullPath: '/demo/g'
      preLoaderRoute: typeof DemoGRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/f': {
      id: '/demo/f'
      path: '/demo/f'
      fullPath: '/demo/f'
      preLoaderRoute: typeof DemoFRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/e': {
      id: '/demo/e'
      path: '/demo/e'
      fullPath: '/demo/e'
      preLoaderRoute: typeof DemoERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/d': {
      id: '/demo/d'
      path: '/demo/d'
      fullPath: '/demo/d'
      preLoaderRoute: typeof DemoDRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/c': {
      id: '/demo/c'
      path: '/demo/c'
      fullPath: '/demo/c'
      preLoaderRoute: typeof DemoCRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/b': {
      id: '/demo/b'
      path: '/demo/b'
      fullPath: '/demo/b'
      preLoaderRoute: typeof DemoBRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/a': {
      id: '/demo/a'
      path: '/demo/a'
      fullPath: '/demo/a'
      preLoaderRoute: typeof DemoARouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/vip': {
      id: '/_main/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof MainVipRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/tutorials': {
      id: '/_main/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof MainTutorialsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/terms': {
      id: '/_main/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof MainTermsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/search': {
      id: '/_main/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof MainSearchRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/reset-password': {
      id: '/_main/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof MainResetPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/privacy': {
      id: '/_main/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof MainPrivacyRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/legal': {
      id: '/_main/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof MainLegalRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/juegos': {
      id: '/_main/juegos'
      path: '/juegos'
      fullPath: '/juegos'
      preLoaderRoute: typeof MainJuegosRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/forgot-password': {
      id: '/_main/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof MainForgotPasswordRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/comics': {
      id: '/_main/comics'
      path: '/comics'
      fullPath: '/comics'
      preLoaderRoute: typeof MainComicsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/chronos': {
      id: '/_main/chronos'
      path: '/chronos'
      fullPath: '/chronos'
      preLoaderRoute: typeof MainChronosRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/terms/': {
      id: '/admin/terms/'
      path: '/terms'
      fullPath: '/admin/terms/'
      preLoaderRoute: typeof AdminTermsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stickers/': {
      id: '/admin/stickers/'
      path: '/stickers'
      fullPath: '/admin/stickers/'
      preLoaderRoute: typeof AdminStickersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile/': {
      id: '/admin/profile/'
      path: '/profile'
      fullPath: '/admin/profile/'
      preLoaderRoute: typeof AdminProfileIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications/': {
      id: '/admin/notifications/'
      path: '/notifications'
      fullPath: '/admin/notifications/'
      preLoaderRoute: typeof AdminNotificationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/media/': {
      id: '/admin/media/'
      path: '/media'
      fullPath: '/admin/media/'
      preLoaderRoute: typeof AdminMediaIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emojis/': {
      id: '/admin/emojis/'
      path: '/emojis'
      fullPath: '/admin/emojis/'
      preLoaderRoute: typeof AdminEmojisIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/creators/': {
      id: '/admin/creators/'
      path: '/creators'
      fullPath: '/admin/creators/'
      preLoaderRoute: typeof AdminCreatorsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comics/': {
      id: '/admin/comics/'
      path: '/comics'
      fullPath: '/admin/comics/'
      preLoaderRoute: typeof AdminComicsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/news/': {
      id: '/_main/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof MainNewsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/patreon/webhook': {
      id: '/api/patreon/webhook'
      path: '/api/patreon/webhook'
      fullPath: '/api/patreon/webhook'
      preLoaderRoute: typeof ApiPatreonWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/manage': {
      id: '/admin/users/manage'
      path: '/users/manage'
      fullPath: '/admin/users/manage'
      preLoaderRoute: typeof AdminUsersManageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/terms/create': {
      id: '/admin/terms/create'
      path: '/terms/create'
      fullPath: '/admin/terms/create'
      preLoaderRoute: typeof AdminTermsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stickers/create': {
      id: '/admin/stickers/create'
      path: '/stickers/create'
      fullPath: '/admin/stickers/create'
      preLoaderRoute: typeof AdminStickersCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/site/marquee': {
      id: '/admin/site/marquee'
      path: '/site/marquee'
      fullPath: '/admin/site/marquee'
      preLoaderRoute: typeof AdminSiteMarqueeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile/roles': {
      id: '/admin/profile/roles'
      path: '/profile/roles'
      fullPath: '/admin/profile/roles'
      preLoaderRoute: typeof AdminProfileRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/profile/emblems': {
      id: '/admin/profile/emblems'
      path: '/profile/emblems'
      fullPath: '/admin/profile/emblems'
      preLoaderRoute: typeof AdminProfileEmblemsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/create': {
      id: '/admin/posts/create'
      path: '/posts/create'
      fullPath: '/admin/posts/create'
      preLoaderRoute: typeof AdminPostsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/pages/$slug': {
      id: '/admin/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/admin/pages/$slug'
      preLoaderRoute: typeof AdminPagesSlugRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extras/weekly': {
      id: '/admin/extras/weekly'
      path: '/extras/weekly'
      fullPath: '/admin/extras/weekly'
      preLoaderRoute: typeof AdminExtrasWeeklyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extras/tutorials': {
      id: '/admin/extras/tutorials'
      path: '/extras/tutorials'
      fullPath: '/admin/extras/tutorials'
      preLoaderRoute: typeof AdminExtrasTutorialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extras/featured': {
      id: '/admin/extras/featured'
      path: '/extras/featured'
      fullPath: '/admin/extras/featured'
      preLoaderRoute: typeof AdminExtrasFeaturedRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/extras/engagement': {
      id: '/admin/extras/engagement'
      path: '/extras/engagement'
      fullPath: '/admin/extras/engagement'
      preLoaderRoute: typeof AdminExtrasEngagementRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emojis/create': {
      id: '/admin/emojis/create'
      path: '/emojis/create'
      fullPath: '/admin/emojis/create'
      preLoaderRoute: typeof AdminEmojisCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comics/create': {
      id: '/admin/comics/create'
      path: '/comics/create'
      fullPath: '/admin/comics/create'
      preLoaderRoute: typeof AdminComicsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/chronos/edit': {
      id: '/admin/chronos/edit'
      path: '/chronos/edit'
      fullPath: '/admin/chronos/edit'
      preLoaderRoute: typeof AdminChronosEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/user/$id': {
      id: '/_main/user/$id'
      path: '/user/$id'
      fullPath: '/user/$id'
      preLoaderRoute: typeof MainUserIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/post/$id': {
      id: '/_main/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof MainPostIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/news/$id': {
      id: '/_main/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof MainNewsIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/admin/notifications/articles/': {
      id: '/admin/notifications/articles/'
      path: '/notifications/articles'
      fullPath: '/admin/notifications/articles/'
      preLoaderRoute: typeof AdminNotificationsArticlesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications/announcements/': {
      id: '/admin/notifications/announcements/'
      path: '/notifications/announcements'
      fullPath: '/admin/notifications/announcements/'
      preLoaderRoute: typeof AdminNotificationsAnnouncementsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stickers/$id/edit': {
      id: '/admin/stickers/$id/edit'
      path: '/stickers/$id/edit'
      fullPath: '/admin/stickers/$id/edit'
      preLoaderRoute: typeof AdminStickersIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts/edit/$id': {
      id: '/admin/posts/edit/$id'
      path: '/posts/edit/$id'
      fullPath: '/admin/posts/edit/$id'
      preLoaderRoute: typeof AdminPostsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications/articles/create': {
      id: '/admin/notifications/articles/create'
      path: '/notifications/articles/create'
      fullPath: '/admin/notifications/articles/create'
      preLoaderRoute: typeof AdminNotificationsArticlesCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notifications/announcements/create': {
      id: '/admin/notifications/announcements/create'
      path: '/notifications/announcements/create'
      fullPath: '/admin/notifications/announcements/create'
      preLoaderRoute: typeof AdminNotificationsAnnouncementsCreateRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/emojis/$id/edit': {
      id: '/admin/emojis/$id/edit'
      path: '/emojis/$id/edit'
      fullPath: '/admin/emojis/$id/edit'
      preLoaderRoute: typeof AdminEmojisIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/comics/edit/$id': {
      id: '/admin/comics/edit/$id'
      path: '/comics/edit/$id'
      fullPath: '/admin/comics/edit/$id'
      preLoaderRoute: typeof AdminComicsEditIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_main/post/reviews/$id': {
      id: '/_main/post/reviews/$id'
      path: '/post/reviews/$id'
      fullPath: '/post/reviews/$id'
      preLoaderRoute: typeof MainPostReviewsIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainChronosRoute: typeof MainChronosRoute
  MainComicsRoute: typeof MainComicsRoute
  MainForgotPasswordRoute: typeof MainForgotPasswordRoute
  MainJuegosRoute: typeof MainJuegosRoute
  MainLegalRoute: typeof MainLegalRoute
  MainPrivacyRoute: typeof MainPrivacyRoute
  MainProfileRoute: typeof MainProfileRoute
  MainResetPasswordRoute: typeof MainResetPasswordRoute
  MainSearchRoute: typeof MainSearchRoute
  MainTermsRoute: typeof MainTermsRoute
  MainTutorialsRoute: typeof MainTutorialsRoute
  MainVipRoute: typeof MainVipRoute
  MainIndexRoute: typeof MainIndexRoute
  MainNewsIdRoute: typeof MainNewsIdRoute
  MainPostIdRoute: typeof MainPostIdRoute
  MainUserIdRoute: typeof MainUserIdRoute
  MainNewsIndexRoute: typeof MainNewsIndexRoute
  MainPostReviewsIdRoute: typeof MainPostReviewsIdRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainChronosRoute: MainChronosRoute,
  MainComicsRoute: MainComicsRoute,
  MainForgotPasswordRoute: MainForgotPasswordRoute,
  MainJuegosRoute: MainJuegosRoute,
  MainLegalRoute: MainLegalRoute,
  MainPrivacyRoute: MainPrivacyRoute,
  MainProfileRoute: MainProfileRoute,
  MainResetPasswordRoute: MainResetPasswordRoute,
  MainSearchRoute: MainSearchRoute,
  MainTermsRoute: MainTermsRoute,
  MainTutorialsRoute: MainTutorialsRoute,
  MainVipRoute: MainVipRoute,
  MainIndexRoute: MainIndexRoute,
  MainNewsIdRoute: MainNewsIdRoute,
  MainPostIdRoute: MainPostIdRoute,
  MainUserIdRoute: MainUserIdRoute,
  MainNewsIndexRoute: MainNewsIndexRoute,
  MainPostReviewsIdRoute: MainPostReviewsIdRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminChronosEditRoute: typeof AdminChronosEditRoute
  AdminComicsCreateRoute: typeof AdminComicsCreateRoute
  AdminEmojisCreateRoute: typeof AdminEmojisCreateRoute
  AdminExtrasEngagementRoute: typeof AdminExtrasEngagementRoute
  AdminExtrasFeaturedRoute: typeof AdminExtrasFeaturedRoute
  AdminExtrasTutorialsRoute: typeof AdminExtrasTutorialsRoute
  AdminExtrasWeeklyRoute: typeof AdminExtrasWeeklyRoute
  AdminPagesSlugRoute: typeof AdminPagesSlugRoute
  AdminPostsCreateRoute: typeof AdminPostsCreateRoute
  AdminProfileEmblemsRoute: typeof AdminProfileEmblemsRoute
  AdminProfileRolesRoute: typeof AdminProfileRolesRoute
  AdminSiteMarqueeRoute: typeof AdminSiteMarqueeRoute
  AdminStickersCreateRoute: typeof AdminStickersCreateRoute
  AdminTermsCreateRoute: typeof AdminTermsCreateRoute
  AdminUsersManageRoute: typeof AdminUsersManageRoute
  AdminComicsIndexRoute: typeof AdminComicsIndexRoute
  AdminCreatorsIndexRoute: typeof AdminCreatorsIndexRoute
  AdminEmojisIndexRoute: typeof AdminEmojisIndexRoute
  AdminMediaIndexRoute: typeof AdminMediaIndexRoute
  AdminNotificationsIndexRoute: typeof AdminNotificationsIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminProfileIndexRoute: typeof AdminProfileIndexRoute
  AdminStickersIndexRoute: typeof AdminStickersIndexRoute
  AdminTermsIndexRoute: typeof AdminTermsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminComicsEditIdRoute: typeof AdminComicsEditIdRoute
  AdminEmojisIdEditRoute: typeof AdminEmojisIdEditRoute
  AdminNotificationsAnnouncementsCreateRoute: typeof AdminNotificationsAnnouncementsCreateRoute
  AdminNotificationsArticlesCreateRoute: typeof AdminNotificationsArticlesCreateRoute
  AdminPostsEditIdRoute: typeof AdminPostsEditIdRoute
  AdminStickersIdEditRoute: typeof AdminStickersIdEditRoute
  AdminNotificationsAnnouncementsIndexRoute: typeof AdminNotificationsAnnouncementsIndexRoute
  AdminNotificationsArticlesIndexRoute: typeof AdminNotificationsArticlesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminChronosEditRoute: AdminChronosEditRoute,
  AdminComicsCreateRoute: AdminComicsCreateRoute,
  AdminEmojisCreateRoute: AdminEmojisCreateRoute,
  AdminExtrasEngagementRoute: AdminExtrasEngagementRoute,
  AdminExtrasFeaturedRoute: AdminExtrasFeaturedRoute,
  AdminExtrasTutorialsRoute: AdminExtrasTutorialsRoute,
  AdminExtrasWeeklyRoute: AdminExtrasWeeklyRoute,
  AdminPagesSlugRoute: AdminPagesSlugRoute,
  AdminPostsCreateRoute: AdminPostsCreateRoute,
  AdminProfileEmblemsRoute: AdminProfileEmblemsRoute,
  AdminProfileRolesRoute: AdminProfileRolesRoute,
  AdminSiteMarqueeRoute: AdminSiteMarqueeRoute,
  AdminStickersCreateRoute: AdminStickersCreateRoute,
  AdminTermsCreateRoute: AdminTermsCreateRoute,
  AdminUsersManageRoute: AdminUsersManageRoute,
  AdminComicsIndexRoute: AdminComicsIndexRoute,
  AdminCreatorsIndexRoute: AdminCreatorsIndexRoute,
  AdminEmojisIndexRoute: AdminEmojisIndexRoute,
  AdminMediaIndexRoute: AdminMediaIndexRoute,
  AdminNotificationsIndexRoute: AdminNotificationsIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminProfileIndexRoute: AdminProfileIndexRoute,
  AdminStickersIndexRoute: AdminStickersIndexRoute,
  AdminTermsIndexRoute: AdminTermsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminComicsEditIdRoute: AdminComicsEditIdRoute,
  AdminEmojisIdEditRoute: AdminEmojisIdEditRoute,
  AdminNotificationsAnnouncementsCreateRoute:
    AdminNotificationsAnnouncementsCreateRoute,
  AdminNotificationsArticlesCreateRoute: AdminNotificationsArticlesCreateRoute,
  AdminPostsEditIdRoute: AdminPostsEditIdRoute,
  AdminStickersIdEditRoute: AdminStickersIdEditRoute,
  AdminNotificationsAnnouncementsIndexRoute:
    AdminNotificationsAnnouncementsIndexRoute,
  AdminNotificationsArticlesIndexRoute: AdminNotificationsArticlesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiHealthRoute: ApiHealthRoute,
  DemoARoute: DemoARoute,
  DemoBRoute: DemoBRoute,
  DemoCRoute: DemoCRoute,
  DemoDRoute: DemoDRoute,
  DemoERoute: DemoERoute,
  DemoFRoute: DemoFRoute,
  DemoGRoute: DemoGRoute,
  DemoHRoute: DemoHRoute,
  DemoIRoute: DemoIRoute,
  DemoJRoute: DemoJRoute,
  DemoKRoute: DemoKRoute,
  DemoLRoute: DemoLRoute,
  DemoMRoute: DemoMRoute,
  DemoNRoute: DemoNRoute,
  DemoIndexRoute: DemoIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPatreonWebhookRoute: ApiPatreonWebhookRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
